apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: "project3-"
spec:
  ports:
  - name: default
    portPolicy: Dynamic
    containerPort: 7654
  template:
    spec:
      containers:
      - name: project3-server
        image: docker.io/winfanpum/project3_server:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "50m"
